import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Welcome to <a href="carechange.com">CareChange</a>
        </h1>
        <p className="text-xl font-bold">
          Where we make it easy to make clinical reports by simply pressing yes
          and no to a series of questions.
        </p>
      </main>
    </>
  );
}
